### ISSUE TITLE
[BLOCKS #89, #102] Update Transaction GQL Schema, add additional mutations/queries/schema fields

### ISSUE THREAD

**Issue by Maverick17user** [Compoundfolio/investing-root#91]
### Fields

**Fields to add**
- [ ] `id`
- [ ] `userTransactionType` - either `FISCAL_TRANSACTION` or `TRADE_OPERATION`
- [ ] `stockExcange` - **example**: 'ARCA' / 'MOSX' / 'NASDAQ'
- [ ] `exchangeCountry`- **example**: 'US' / 'NO' / 'UK'
- [ ] `assetName` - **example**: 'Apple Inc.' / 'Microsoft' / 'Bitcoin'
- [ ] `handlingTypes` 
  - --TODO: refine wording--
  -  Should be and Array of unique values - "HANDLY_ADDED"  | "HANDLY_UPLOADED" | "HANDLY_EDITED". 
  - **Example** - ["HANDLY_ADDED"] / ["HANDLY_UPLOADED", "HANDLY_EDITED"]. 
  - See [Figma for updatable types](https://www.figma.com/file/dqpGvDxgbH8O6v6okHLwbJ/Compoundfolio---Stage-1?type=design&node-id=731-9566&mode=design&t=nNpnb7Yt9StMENXR-4)
- [ ] Add documenbtation to user transaction type

**Fields to remove**
- [ ] `fiscalTransactionId`
- [ ] `tradeOperationId`

**Fields to discuss & add**
- [ ] ~~fee~~ comission - Trade-type operations (such as Buy/Sell/Funding/Withdrawal) have fees. Check-out https://www.figma.com/file/dqpGvDxgbH8O6v6okHLwbJ/Compoundfolio---Stage-1?type=design&node-id=1594-9404&mode=design&t=nNpnb7Yt9StMENXR-4

#### Comissions
- Comission is a separate transaciton, but it is **linked** to the trade it originates from
- When parsing EXANTE report, read comissions from Trades table, but ignore instrument-related comissions in fiscal transaction tables
- See wiki and check how it works for freedomfinance
- For reverted dividents, are you sure you correnctly parse commissions? They look negative

**Existing fields to discuss**
- [ ] TODO: create ticket to LOG unrecognized transaction types, and unit tests! in this ticket, also difine work for frontend
- [x] ~~unrecognizedType - not clear what is it~~
- [x] `summ.amount`  
1. is in a one share price, or WHOLE, TOTAL transaction cost. 
2. Can/should it be negative, in case it's commission/tax/sell with loss/withdrawal?
- [ ] `userTransactionType`

- [ ] Required changes for TransactionType:
  - [ ] "is negative" - indicates if summ is expected to be negative
  - [ ] "TAX' -> "DIVIDEND_TAX"
  - [ ] Separate funding and withdrawal, but make withdrawal negative (same for mutations)

- [ ] TODO: Create ticket to ask user if he would like to leave us the report in case of the error

**Comment by alexesmet** [comment]
Closing issue because it was created for a wrong environment. Any backend API update requests are very welcome, but must be based on the most recent schema.

**Comment by Maverick17user** [comment]
@alexesmet Updated requirements. Will discuss tomorrow, feel free to review and prepare questions

Funny meme:

![Image](https://github.com/Compoundfolio/investing-root/assets/30416868/48be16dc-5b4f-4f4a-8c02-7d33c66db037)

**Comment by alexesmet** [comment]
### Updated api
 - Add `id`
 - Add `userTransactionClass` enum (either `TRADE_OPERATION` or `FISCAL_TRANSACTION`)
 - Add `stockExchange`, appears in TRADES, but hardcoded for now (will be tech debt)
 - Add `exchangeCountryCode`, appears in TRADES, but hardcoded for now (will be tech debt)
 - Add `assetName`, appears in TRADES, but hardcoded for now (will be tech debt)
 - Add `transactionHistoryMarker` with values `CREATED_MANUALLY`, `CREATED_FROM_REPORT`, `CREATED_FROM_REPORT_AND_UPDATED_MANUALLY`
 - Add `commission` field that optionally contains an other UserTransaction.
 - Remove `fiscalTransactionId`
 - Remove `tradeOperationId`
 - Renamed all "comission" to "commission"
